### ISSUE TITLE
macOS 27: bare LLVM `fence` crashes the AGX back-end compiler (XPC_ERROR_CONNECTION_INTERRUPTED)

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/Metal.jl#968]
## Summary

On macOS 27.0 (26A428), Apple's AGX back-end compiler aborts on any bare LLVM `fence` instruction. Metal.jl surfaces this as:

```
Compilation to native code failed; see below for details.
caused by: NSError: Compilation failed due to an interrupted connection:
XPC_ERROR_CONNECTION_INTERRUPTED. This error occurred after multiple retries. (AGXMetal13_3, ...)
```

The XPC error is only the symptom: `MTLCompilerService` crashes and Metal retries. The same kernels compile fine on macOS 26.6.2.

This first showed up in the KernelAbstractions.jl `fences` atomics testset (build 2073 on the CI minis that were upgraded to macOS 27), whose kernel calls `UnsafeAtomics.fence`, i.e. `Core.Intrinsics.atomic_fence`, which GPUCompiler passes through as a plain `fence`.

## Root cause

The crash reports in `~/Library/Logs/DiagnosticReports/MTLCompilerService-*.ips` show a fatal error from instruction selection in the AGX backend:

```
cannot select: 113 5, 1
Context:
113 5, 1
(in function: agc.main)
```

Stack: `MTLCodeGenServiceBuildRequest` → `AGXCompilerCore AGCLLVMCtx::compile` → `AGXCompilePlan::execute` → `MachineFunctionPass::runOnFunction` → `llvm::report_fatal_error` → `abort_with_reason`.

The dumped AIR contains bare `fence release` / `fence acquire` next to the `air.atomic.global.{load,store}` calls. Presumably Apple's frontend never emits bare fences (only `air.atomic.fence` and barrier intrinsics), so the macOS 27 backend dropped support.

## What was tested (M1 Mac mini, macOS 27.0 26A428, Metal.jl main)

- Trivial kernels compile fine, with and without binary archives.
- The fence kernel fails identically with `JULIA_METAL_BINARY_ARCHIVES=false`, so `archived_pipeline` in the backtrace is incidental.
- **Every** bare fence crashes the compiler: `acquire`, `release`, `acquire_release`, `sequentially_consistent`, with any syncscope (`singlethread`, `agent`, `workgroup`).
- `Metal.atomic_thread_fence`, which emits `air.atomic.fence`, compiles for all orderings (relaxed, acquire, release, seq_cst).

## MWE

```julia
using Metal
function kf(a)
    Core.Intrinsics.atomic_fence(:release)
    a[1] = 1
    return
end
@metal kf(Metal.zeros(Int32, 1))
```

## Proposed fix

In GPUCompiler's Metal `finish_ir!`, next to the existing atomic ABI rewriting, lower each `fence` to a call to `air.atomic.fence(flags, order, scope)` using the enum values already defined in `src/device/intrinsics/synchronization.jl` (relaxed=0, acquire=2, release=3, acq_rel=4, seq_cst=5; scope device=2; `MemoryFlagDevice`).

Caveat: acquire/release orderings of `air.atomic.fence` require MSL ≥ 4.1, so on older targets either keep the bare fence (which works there) or widen to seq_cst.

Metal.jl's own test suite has no bare-fence kernel, which is why only KernelAbstractions caught this; a test using `Core.Intrinsics.atomic_fence` in a kernel would cover it.
